name: pokemon-api
services:
  db:
    image: postgres:18
    container_name: pokemon_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "pokemon_db"]
      interval: 5s
      retries: 5

  db-seed:
    image: postgres:18
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./deploy/seed.sql:/seed.sql
    entrypoint:
      ["psql", "-h", "db", "-U", "admin", "-d", "pokemon_db", "-f", "/seed.sql"]
    environment:
      PGPASSWORD: admin

  backend:
    image: mahveesha/pokemon-api-backend:${IMAGE_TAG:-main}
    depends_on:
      db-seed:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@db:5432/pokemon_db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
